project:
  type: website


website:
  title: "PEG study training"
  twitter-card: true
  bread-crumbs: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    left:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: calendar-check-fill
        text: Timeline
        href: timeline.qmd
      - icon: info-circle-fill
        text: About
        href: about.qmd
    right:
      # - icon: github
      #   url: https://ivangong24.github.io/
      - icon: browser-safari
        text: PEG Study website
        url: https://www.pegstudy.com/
      - icon: envelope
        text: pegstudy@mednet.ucla.edu
        url: pegstudy@mednet.ucla.edu
      - icon: telephone
        text: +1-866-519-1795  
      
          
  sidebar:
    style: "docked"
    border: true
    contents: posts
        


      
execute:
  freeze: auto

format:
  html:
    theme: 
      light: litera
      dark: slate
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    