project:
  type: website


website:
  title: "PEG study training"
  favicon: images/peg_logo_favi.png
  twitter-card: true
  open-graph: true
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  reader-mode: false
  page-footer: 
    center: "Â© 2024 PEG Training | All rights reserved."
          
  navbar:
    left:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: calendar-check-fill
        text: Timeline
        href: timeline.qmd
      - icon: info-circle-fill
        text: About
        href: about.qmd
    right:
      # - icon: github
      #   url: https://ivangong24.github.io/
      - icon: browser-safari
        text: PEG Study website
        url: https://www.pegstudy.com/
      - text: Contact us
        menu: 
          - icon: envelope
            text: pegstudy@mednet.ucla.edu
            href: mailto:pegstudy@mednet.ucla.edu
          - icon: telephone
            text: +1-866-519-1795  
            href: tel:866-519-1795
      - icon: github
        href: https://github.com/ucla-peg-2024/peg_training
        aria-label: GitHub

  sidebar:
    style: "docked"
    border: true
    contents: posts
        

execute:
  freeze: auto

format:
  html:
    theme: 
      light: flatly
      dark: [darkly, theme-dark.scss]
    highlight-style: github
    code-copy: true
    code-overflow: wrap
    #css: styles.css
    toc: true
    